### DISCUSSION TITLE
Passphrase for /root/.ssh/id_rsa required with provided deploy ssh private key

### DISCUSSION THREAD

**Discussion by kirbytwister** [hosted-domains/stack-deploy-action#10] [Q&A]
Here's my github action
```
deploy:
    runs-on: ubuntu-latest
    needs:
      - push_image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile

      - name: Docker Stack Deploy
        uses: cssnr/stack-deploy-action@v1
        with:
          name: osu-team-sheets
          file: docker-stack.yaml
          host: osusheets.team
          user: deploy
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          env_file: ./envfile
```
When it comes to executing this job, it fails after trying to enter a pass for `/root/.ssh/id_rsa`
My private ssh is listed in `authorized_keys` inside my VPS where this user is defined. The key however was generated not as rsa but as ed_25519

![image](https://github.com/user-attachments/assets/e5e087a4-974e-48ca-aa5b-82415f79511d)
