### DISCUSSION TITLE
--with-registry-auth

### DISCUSSION THREAD

**Discussion by sylvain-barrepersyn** [hosted-domains/stack-deploy-action#4] [Feature Requests]
Hello maintainers ! 

I want to use this tool to deploy stack on my VPS but the packages are private and owned by an organization that I own in my turn.

Packages must be privates and so, I want to know if it's possible to add a parameter `args` which will be added at the end of command `docker stack deploy`.

```yaml
    - name: Docker Stack Deploy
      uses: cssnr/stack-deploy-action@v1
      with:
        name: my-stack-name
        file: docker-stack.yaml
        host: my-app.com
        user: vps-user
        ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
        args: "--with-registry-auth"
``` 

It will be added at the end of command [here](https://github.com/cssnr/stack-deploy-action/blob/1dae9f655527e6a141122886ae64e24afb6d6274/src/main.sh#L64) as described ⬇️.
        
```shell
# ...
docker stack deploy -c "${INPUT_FILE}" "${INPUT_NAME} ${ARGS}"
```

| input    | required | default               | description                              |
| -------- | -------- | --------------------- | ---------------------------------------- |
| host     | **Yes**  | -                     | Remote Docker hostname                   |
| port     | No       | `22`                  | Remote Docker port                       |
| user     | **Yes**  | -                     | Remote Docker username                   |
| pass     | No       | -                     | Remote Docker password \*                |
| ssh_key  | No       | -                     | Remote SSH Key file \*                   |
| file     | No       | `docker-compose.yaml` | Docker Compose file                      |
| name     | **Yes**  | -                     | Docker Stack name                        |
| env_file | No       | -                     | Docker Environment file                  |
| args    | No       | -                     | Args for command `docker stock deploy` (added to the end)   |

---

Other possible solution is to permit only with registry auth by adding a parameter `registry_auth`: 

```yaml
    - name: Docker Stack Deploy
      uses: cssnr/stack-deploy-action@v1
      with:
        name: my-stack-name
        file: docker-stack.yaml
        host: my-app.com
        user: vps-user
        ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
        registry_auth: true
``` 

| input            | required | default               | description                              |
| ---------------- | -------- | --------------------- | ---------------------------------------- |
| host             | **Yes**  | -                     | Remote Docker hostname                   |
| port             | No       | `22`                  | Remote Docker port                       |
| user             | **Yes**  | -                     | Remote Docker username                   |
| pass             | No       | -                     | Remote Docker password \*                |
| ssh_key          | No       | -                     | Remote SSH Key file \*                   |
| file             | No       | `docker-compose.yaml` | Docker Compose file                      |
| name             | **Yes**  | -                     | Docker Stack name                        |
| env_file         | No       | -                     | Docker Environment file                       |
| registry_auth    | No       | `false`               | Activate registry authentication at deployment  |
