### DISCUSSION TITLE
getaddrinfo ***: Name does not resolve

### DISCUSSION THREAD

**Discussion by davidarny** [hosted-domains/stack-deploy-action#6] [Q&A]
Hello and thanks for building this action!

However, I'm getting `getaddrinfo ***: Name does not resolve` error, not sure what is the reason.

This is my config:

```yaml
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-and-push-images
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create env file
        run: |
          echo "GIT_COMMIT_HASH=${{ github.sha }}" >> ./envfile
          echo "REMOTE_HOST=${{ secrets.REMOTE_HOST }}" >> ./envfile
          echo "CDN_HOST=${{ secrets.CDN_HOST }}" >> ./envfile
          echo "CODENAME=${{ secrets.CODENAME }}" >> ./envfile

      - name: Deploy stack
        uses: cssnr/stack-deploy-action@v1
        with:
          name: ${{ secrets.CODENAME }}
          file: compose.yaml
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          ssh_key: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          env_file: ./envfile
```

Double checked repository secrets, everything is fine. Any ideas?
